-- GENERATED by mapgen/lib/wang-template-writer.mjs — do not edit
-- Thin shim only: file writes live in init.lua (sandbox here has no io).
dofile_once("data/scripts/biome_scripts.lua")

RegisterSpawnFunction(0xffff10ff, "lab_tile_0")
function lab_tile_0(x, y) lab_log(0, 1, 0,0,0,0,0,0, x, y) end
RegisterSpawnFunction(0xffff1ef1, "lab_tile_1")
function lab_tile_1(x, y) lab_log(1, 1, 0,1,0,0,0,0, x, y) end
RegisterSpawnFunction(0xffff2ce3, "lab_tile_2")
function lab_tile_2(x, y) lab_log(2, 1, 0,0,0,1,0,0, x, y) end
RegisterSpawnFunction(0xffff3ad5, "lab_tile_3")
function lab_tile_3(x, y) lab_log(3, 1, 0,1,0,1,0,0, x, y) end
RegisterSpawnFunction(0xffff48c7, "lab_tile_4")
function lab_tile_4(x, y) lab_log(4, 1, 0,0,0,0,0,1, x, y) end
RegisterSpawnFunction(0xffff56b9, "lab_tile_5")
function lab_tile_5(x, y) lab_log(5, 1, 0,1,0,0,0,1, x, y) end
RegisterSpawnFunction(0xffff64ab, "lab_tile_6")
function lab_tile_6(x, y) lab_log(6, 1, 0,0,0,1,0,1, x, y) end
RegisterSpawnFunction(0xffff729d, "lab_tile_7")
function lab_tile_7(x, y) lab_log(7, 1, 0,1,0,1,0,1, x, y) end
RegisterSpawnFunction(0xffff808f, "lab_tile_8")
function lab_tile_8(x, y) lab_log(8, 0, 0,0,0,0,0,0, x, y) end
RegisterSpawnFunction(0xffff8e81, "lab_tile_9")
function lab_tile_9(x, y) lab_log(9, 0, 1,0,0,0,0,0, x, y) end
RegisterSpawnFunction(0xffff9c73, "lab_tile_10")
function lab_tile_10(x, y) lab_log(10, 0, 0,0,1,0,0,0, x, y) end
RegisterSpawnFunction(0xffffaa65, "lab_tile_11")
function lab_tile_11(x, y) lab_log(11, 0, 1,0,1,0,0,0, x, y) end
RegisterSpawnFunction(0xffffb857, "lab_tile_12")
function lab_tile_12(x, y) lab_log(12, 0, 0,0,0,0,1,0, x, y) end
RegisterSpawnFunction(0xffffc649, "lab_tile_13")
function lab_tile_13(x, y) lab_log(13, 0, 1,0,0,0,1,0, x, y) end
RegisterSpawnFunction(0xffffd43b, "lab_tile_14")
function lab_tile_14(x, y) lab_log(14, 0, 0,0,1,0,1,0, x, y) end
RegisterSpawnFunction(0xffffe22d, "lab_tile_15")
function lab_tile_15(x, y) lab_log(15, 0, 1,0,1,0,1,0, x, y) end

RegisterSpawnFunction(0xffffeedd, "lab_chunk_init")
function lab_chunk_init(x, y) lab_chunk(x, y) end
