-- GENERATED by mapgen/lib/wang-template-writer.mjs — do not edit
-- Thin shim only: rows go through the game global store (sandbox here has no
-- io and no mod globals). init.lua drains them to the CSV.
dofile_once("data/scripts/biome_scripts.lua")

function lab_emit(fields, x, y)
  local seed = tostring(StatsGetValue("world_seed") or "0")
  local n = tonumber(GlobalsGetValue("wanglab_count", "0") or "0") + 1
  GlobalsSetValue("wanglab_count", tostring(n))
  GlobalsSetValue("wanglab_r_" .. n, seed .. "," .. fields .. "," .. x .. "," .. y)
end

RegisterSpawnFunction(0xffff10ff, "lab_tile_0")
function lab_tile_0(x, y) lab_emit("0,1,0,0,0,0,0,0", x, y) end
RegisterSpawnFunction(0xffff1ef1, "lab_tile_1")
function lab_tile_1(x, y) lab_emit("1,1,0,1,0,0,0,0", x, y) end
RegisterSpawnFunction(0xffff2ce3, "lab_tile_2")
function lab_tile_2(x, y) lab_emit("2,1,0,0,0,1,0,0", x, y) end
RegisterSpawnFunction(0xffff3ad5, "lab_tile_3")
function lab_tile_3(x, y) lab_emit("3,1,0,1,0,1,0,0", x, y) end
RegisterSpawnFunction(0xffff48c7, "lab_tile_4")
function lab_tile_4(x, y) lab_emit("4,1,0,0,0,0,0,1", x, y) end
RegisterSpawnFunction(0xffff56b9, "lab_tile_5")
function lab_tile_5(x, y) lab_emit("5,1,0,1,0,0,0,1", x, y) end
RegisterSpawnFunction(0xffff64ab, "lab_tile_6")
function lab_tile_6(x, y) lab_emit("6,1,0,0,0,1,0,1", x, y) end
RegisterSpawnFunction(0xffff729d, "lab_tile_7")
function lab_tile_7(x, y) lab_emit("7,1,0,1,0,1,0,1", x, y) end
RegisterSpawnFunction(0xffff808f, "lab_tile_8")
function lab_tile_8(x, y) lab_emit("8,0,0,0,0,0,0,0", x, y) end
RegisterSpawnFunction(0xffff8e81, "lab_tile_9")
function lab_tile_9(x, y) lab_emit("9,0,1,0,0,0,0,0", x, y) end
RegisterSpawnFunction(0xffff9c73, "lab_tile_10")
function lab_tile_10(x, y) lab_emit("10,0,0,0,1,0,0,0", x, y) end
RegisterSpawnFunction(0xffffaa65, "lab_tile_11")
function lab_tile_11(x, y) lab_emit("11,0,1,0,1,0,0,0", x, y) end
RegisterSpawnFunction(0xffffb857, "lab_tile_12")
function lab_tile_12(x, y) lab_emit("12,0,0,0,0,0,1,0", x, y) end
RegisterSpawnFunction(0xffffc649, "lab_tile_13")
function lab_tile_13(x, y) lab_emit("13,0,1,0,0,0,1,0", x, y) end
RegisterSpawnFunction(0xffffd43b, "lab_tile_14")
function lab_tile_14(x, y) lab_emit("14,0,0,0,1,0,1,0", x, y) end
RegisterSpawnFunction(0xffffe22d, "lab_tile_15")
function lab_tile_15(x, y) lab_emit("15,0,1,0,1,0,1,0", x, y) end

RegisterSpawnFunction(0xffffeedd, "lab_chunk_init")
function lab_chunk_init(x, y) lab_emit("chunk", x, y) end
